/** If you register a new waypoint, make sure to add it to this list */

REGISTER_WAYPOINT(Waypoint, _("Waypoint"), "", '1 0 0', 1);
REGISTER_WAYPOINT(Helpme, _("Help me!"), "", '1 0.5 0', 1);
REGISTER_WAYPOINT(Here, _("Here"), "", '1 0 0', 1);
REGISTER_WAYPOINT(Danger, _("DANGER"), "", '1 0.5 0', 1);

REGISTER_WAYPOINT(Weapon, _("Weapon"), "", '0 0 0', 1);

REGISTER_WAYPOINT(Exit, _("Exit"), "", '1 0 0', 1);

REGISTER_WAYPOINT(Entity, _("Entity"), "", '1 0 0', 1);

REGISTER_WAYPOINT(Monster, _("Monster"), "", '1 0 0', 1);

REGISTER_WAYPOINT(Death, _("Death"), "", '1 0.5 0', 1);
REGISTER_WAYPOINT(SkillIssue, _("Skill Issue"), "", '1 0.5 0', 1);

REGISTER_WAYPOINT(Tower, "", "td_tower", '1 0 0', 1);
REGISTER_WAYPOINT(Monsters, _("Monsters"), "", '1 0 0', 1);
