// EFFECT(istrail, EFFECT_NAME,     "effectinfo_string")

// jumps done well
EFFECT(0, BLOBSHADOW,               "blobshadow")
EFFECT(0, ENEMY_DIE,                "weapons.enemy_die")
EFFECT(0, ENEMY_HIT,                "weapons.enemy_hit")
EFFECT(0, ITEM_PICKUP,              "weapons.item_pickup")
EFFECT(0, WEAPON_CHARGED,           "weapons.charged")
EFFECT(0, WEAPON_SPIN,              "weapons.spin")
EFFECT(0, WEAPON_JUMP,              "weapons.jump")
